[package]
name = "waifu_pics"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", default-features = false, features = [
	"json",
	"rustls-tls",
] }
