[package]
name = "xkcd"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
reqwest = { version = "0.11", default-features = false, features = [
	"json",
	"rustls-tls",
] }
