[package]
name = "xkcd"
version = "0.1.1"
edition = "2021"

[lib]

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
rand = "0.8"
reqwest = { version = "0.11", default-features = false, features = ["json"] }
